In [1]:
import numpy as np

# Program 1
Generate a 3x4 NumPy array with random integers between 1 and 50.

In [2]:
arr = np.random.randint(1, 50, (3, 4))
arr

array([[45, 44, 20,  6],
       [ 5, 43, 45,  8],
       [27, 33,  7, 37]])

Calculate and print the mean, median, and standard deviation of the array.

In [3]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

26.666666666666668
30.0
15.97567595509568


Print the sum of all elements and the sum of each row.

In [4]:
print(np.sum(arr))
print(np.sum(arr, axis=0))

320
[ 77 120  72  51]


Reshape the 3x4 array into a 2x6 array and print it.

In [5]:
print(np.reshape(arr, (2, 6)))

[[45 44 20  6  5 43]
 [45  8 27 33  7 37]]


# Program 2
Create two (3 * 3) matrices using NumPy and print it. Perform and print the results of the following linear algebra operations.

In [6]:
x = np.random.randint(1, 100, (3, 3))
y = np.random.randint(1, 100, (3, 3))
print(x)
print()
print(y)

[[41 40 78]
 [57  7 52]
 [23 67  2]]

[[49 13 86]
 [85 83 18]
 [71 44 22]]


Matrix addition

In [7]:
print(x + y)

[[ 90  53 164]
 [142  90  70]
 [ 94 111  24]]


Matrix subtraction

In [8]:
print(x - y)

[[ -8  27  -8]
 [-28 -76  34]
 [-48  23 -20]]


Matrix multiplication (element-wise and dot product)

In [9]:
print(x @ y)

[[10947  7285  5962]
 [ 7080  3610  6172]
 [ 6964  5948  3228]]


Transpose of a matrix

In [10]:
print(x.T)
print()
print(y.T)

[[41 57 23]
 [40  7 67]
 [78 52  2]]

[[49 85 71]
 [13 83 44]
 [86 18 22]]


Determinant and inverse (if applicable)

In [11]:
print(np.linalg.det(x))
print()
print(np.linalg.det(y))
print()
print(np.linalg.inv(x))
print()
print(np.linalg.inv(y))

186334.00000000006

-142188.00000000012

[[-0.01862247  0.02761707  0.00823253]
 [ 0.00580678 -0.0091878   0.01241856]
 [ 0.01963141 -0.00980497 -0.01069585]]

[[-0.00727206 -0.02460123  0.04855543]
 [ 0.0041635   0.03536163 -0.04520775]
 [ 0.01514192  0.00867162 -0.02083158]]
